require 'ffi'
require 'phidgets-ffi/phidgets-ffi'
require 'phidgets-ffi/ffi/constants'
require 'phidgets-ffi/ffi/common'
require 'phidgets-ffi/ffi/manager'
require 'phidgets-ffi/ffi/servo'
require 'phidgets-ffi/ffi/interface_kit'

require 'phidgets-ffi/common'
require 'phidgets-ffi/error'
require 'phidgets-ffi/manager'
require 'phidgets-ffi/servo'